### PR TITLE
issue #635

### PR DESCRIPTION
**Pull request by xliii**
Generated unique ID is now added as toast's class if class already present.
Using generated unique ID as selector to only select the current toast.

### CODE REVIEW

**Comment by kevzlou7979** [comment]
First thanks for the Contribution, I checked it and it works well the ID is now generated well.

**Comment by kevzlou7979** [comment]
Also update the PR to be merge on ```release_2.0``` instead of ```master``` branch. Thanks in advance then we can merge this in.

**Comment by xliii** [comment]
Thank you! I have updated the branch to `release_2.0`

**Comment by kevzlou7979** [comment]
Wow great, thanks again.

**Pull request merged**
