### PR TITLE
WIP - Input Field Validation and Error Handling

### PR DESCRIPTION
**Pull request by BenDol**
Initial implementation of field validation and error handling, this allows us to create custom Validators for input fields.

Example Usage:
```java
public class EmailValidator extends RegExValidator {

    public EmailValidator() {
        super("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.(?:[a-zA-Z]{2,6})$", "Not a valid email address.");
    }

    @Override
    public int getPriority() {
        return 0;
    }
}
```
```java
MaterialTextBox textBox = new MaterialText
textBox.addValidator(new EmailValidator());

if(textBox.validate()) {
   GWT.log("This is a valid email address.");
}
```

This is one example of its usage, it supports the GWT Editor pattern too.

Special thanks to @sjardine for letting me use the validation/error handling system he wrote for gwtbootstrap3. All copyrights and credits are retained were it is due.

### CODE REVIEW

**Comment by BenDol** [comment]
Can be seen here http://gwtmaterialdesign.github.io/gwt-material-demo/snapshot/#!errors

**Comment by volgin** [comment]
It may be better to do it this way, avoiding the need to compile the regex every time it is needed:

```
public class EmailValidator extends AbstractValidator<String> {

    private static final String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
    private static final RegExp regex = RegExp.compile(EMAIL_PATTERN);

    public RegExValidator(String pattern) {
        super(Keys.REGEX, new Object[0]);
    }

    public RegExValidator(String pattern, String invalidMessageOverride) {
        super(invalidMessageOverride);
    }

    @Override
    public int getPriority() {
        return Priority.MEDIUM;
    }

    @Override
    public boolean isValid(String value) {
        return value == null || value.isEmpty() || regex.test(value);
    }
}
```
Also note an empty value check. Most GWT widgets do not return null values when empty.

**Comment by BenDol** [comment]
Yeah I will make the `RegExpValidator` store the compiled RegExp object. Good suggestion :+1:

**Comment by BenDol** [comment]
In fact the RegExValidator its already storing the regex object.

**Comment by volgin** [comment]
It's not static, so it compiles every time the setter is called. I imagine you would need only one EmailValidator throughout the app, but in any case you need only one RegExp for email since it never changes.

**Comment by remarkNS** [comment]
I agree 50% with @volgin and 50% with @BenDol . I think RegExValidator should have protected RegExp regex instead of private, EmailValidator should extend RegExValidator and not AbstractValidator, in EmailValidator should exist static PATTERN, and static patternRegex = RegExp.compile(PATTERN); and in constructor of derived class assign regex = patternRegex; so that base class will do actual validation with regexp. This way you can have both static and dynamic patterns working which depend on current situation. The same is with Alphanumeric, Numeric etc. validators.

**Comment by volgin** [comment]
In either case, I suggest fixing the email regex pattern in the demo because people might actually copy it. The pattern being displayed will reject many valid email addresses, e.g. name@example.co.uk.

**Pull request merged**
