### PR TITLE
Added methods from the ListBox to the MaterialListBox.

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
Added methods from the ListBox class from GWT to the MaterialListBox (since MaterialListBox doesn't extend ListBox anymore).

Also added javadocs to the delegate methods, and created some utility methods for easier use of the component.

### CODE REVIEW

**Comment by kevzlou7979** [comment]
@gilberto-torrezan  First thanks for the PR, can you please apply this on master branch instead on release 1.5 thanks

**Comment by gilberto-torrezan** [comment]
@kevzlou7979 Is that ok to do so? The change of MaterialListBox super class (from ListBox to MaterialWidget) is a breaking change, shouldn't be on master in my opinion before 1.5.

**Comment by kevzlou7979** [comment]
@gilberto-torrezan I checked the MaterialListBox master branch the refactoring also has been applied. Reference https://github.com/GwtMaterialDesign/gwt-material/blob/master/gwt-material/src/main/java/gwt/material/design/client/ui/MaterialListBox.java

**Comment by kevzlou7979** [comment]
Also does the pr supports nested <g:item> feature on MaterialListBox?

**Comment by gilberto-torrezan** [comment]
Ok, I think that change should be listed on a release notes or something, in my projects it created a big impact. I'll close this PR and create another, just a minute.

**Pull request closed without merging**
