### PR TITLE
WIP - Resource improvements, refactoring, fixes and clean up

### PR DESCRIPTION
**Pull request by BenDol**
Reworked how we load material resources, now split up to provide better options. Module entrypoints are now broken into GwtMaterialDesign, GwtMaterialDesignDebug, GwtMaterialWithJQuery, GwtMaterialWithJQueryDebug, these modules make it possible to load the Javascript for debugging (non-minified and sourceUrl for Chrome debugger) and also optional *WithJQuery since material design should assume you are managing the loading of JQuery but provide the option if you need it. Also organized all the resources to css, js, img rather than having them all in the one directory.

See the module [files](https://github.com/BenDol/gwt-material/tree/bd_contrib/src/main/resources/gwt/material/design)
See new [EntryPoints](https://github.com/BenDol/gwt-material/tree/bd_contrib/src/main/java/gwt/material/design/client)
See new resource [packages](https://github.com/BenDol/gwt-material/tree/bd_contrib/src/main/resources/gwt/material/design/client/resources)

Improved the Waves loading to ensure proper initiation, now uses static Waves class which checks if the element is attached to the DOM and if not will bind the wave init to the widgets attach handler.

General Changes:
* Updated the pom to include sources and added nodoclint profile.
* Removed some code gruff throughout all the sources.
* General fixes where found including some missing functionality.
* Changed HasType to include generic extends Type.
* All Type enums now implement Type and Style.HasCssName.

### CODE REVIEW

**Comment by kevzlou7979** [comment]
Hi @BenDol  Thank you very much for the pull request

**Comment by BenDol** [comment]
No problem, care in mind this is still a WIP (work in progress), so as long as you don't mind that some changes could be breaking. That is until I get to do a full test of each component.

Didn't expect a merge yet haha but that is fine, I have just committed some more refactoring. Will open a new PR. You can merge this one and start testing if you like, but it will almost certainly break a lot og things since I am rewriting a large majority of the UI code.

**Comment by kevzlou7979** [comment]
Ok I have commit and pushed some unused imports  https://github.com/GwtMaterialDesign/gwt-material/commit/240c68a9181f7f8d65c94d8fe72e00eb69d522f4. I tried to rerun my sample test app, and it works if we use ```xml <inherits name="gwt.material.design.GwtMaterialWithJQuery" />``` instead of the old one. Is this correct?

**Comment by BenDol** [comment]
That is correct, if you need to load JQuery (i.e. you haven't already loaded it). This keeps the size of the application down since if you already load it with another dependency you end up compiling it multiple times as a ClientBundle resource.

Note that there might be crashing bugs, I am about to sleep now but first thing when I wake I will resume testing and ensure all components are working as they are in the demo page. I will do all the ones that I can figure out. Perhaps you could write some javadocs up for widgets like MaterialTab etc to help me understand how the widget is mean't to function (I can figure it out, but it speeds things up). Anyway, my Skype if you need to contact me about anything: `ben.dol`.

**Comment by kevzlou7979** [comment]
Hi Ben Dol,

Thanks for this information, Im trying to test all of those modifications.
I found some specific problems or issues:

*Waves*
- duplicates the waves-waves classname on intialization e.g waves="LIGHT"
-> waves-waves-light

*Tooltip *
- How can we set the tooltip on UiBinder? I dont see any posibility.

*Autocomplete (With Image) *
- No image is initialized on Contact Autocomplete Demo

*Chips (Autocomplete integration)*
- Can select or click chips to make it active

*Button*
- setIconType(IconType) will add btn classname which is not correct.

Im finalizing the JavaDocs.
If you need help , I added you on skype.
But its better if we can talk on Hangouts, my hangout account is
kevzlou7979@gmail.com.

Have a great day!
Mark

**Pull request merged**
