### PR TITLE
Release 2.1

### PR DESCRIPTION
**Pull request by kbrockhoff**
Fix for issue #628 which automatically generates a blank option item if allowBlank=true

### CODE REVIEW

**Comment by BenDol** [comment]
👍

**Comment by kevzlou7979** [comment]
Thanks for the contribution will review this

**Comment by kevzlou7979** [comment]
-[ ] All CI checked passed
-[ ] All Unit Test passed
-[ ] Demo showcase passed
-[ ] Errai support passed

**Comment by nseb** [comment]
Set Null value in MaterialComboBox, not working in 2.1 Release

**Pull request merged**
