### PR TITLE
Fixed: Unable to add a CloseHandler to a MaterialModal

### PR DESCRIPTION
**Pull request by wkok**
Fixed issue where one was unable to add a CloseHandler to a MaterialModal.

The CloseHandler passed in to addCloseHandler() was ignored and replaced with a new CloseHandler.
It was working in a previous commit, I've merely reverted this method. If my understanding of the functionality is incorrect, please ignore.

### CODE REVIEW

**Comment by BenDol** [comment]
Can you create this PR against `release_1.6.0`? Unless @kevzlou7979 thinks its urgent enough for a 1.5.2 patch. Would need to decide.

**Comment by kevzlou7979** [comment]
Ok will open a 1.5.2 branch and milestone

**Comment by kevzlou7979** [comment]
Created branch re;ease 1.5.2 and updated the readme about the current snapshot

**Comment by wkok** [comment]
Closing this PR to create new one on branch 1.5.2

**Pull request closed without merging**
