### PR TITLE
Material auto complete

### PR DESCRIPTION
**Pull request by guaido79**
Using the material autocomplete we have found some little issues:
* Not really material design (using the old SuggesDisplay)
* When using directInputAllowed="true" and a suggestionbox is open the user is forced to choose a result  (ex. Listing: John Brown and John Red, it's not possible to choose John)
* A lot of work to do resize, if it is appearing so bad please suggest better implementation :)

### CODE REVIEW

**Comment by kevzlou7979** [comment]
Ok thanks @guaido79 we will review this. Thanks for the PR

**Comment by BenDol** [comment]
Seems to me like the MaterialAutocomplete should be an addin widget since its not a component of the materializecss library. @kevzlou7979 do we plan on moving this widget out for the 1.5 release? If so we will accept this PR and implement it in the addins library for testing. Note that the addins library will be deploying a 1.5-SNAPSHOT (if it hasn't already).

**Comment by kevzlou7979** [comment]
@BenDol  Yes im working the migration of autocomplete to be an addin widget. @guaido79 thanks for the contribution. I will ping you once its done so that we can close and merge this feature on 1.5 release.

**Comment by kevzlou7979** [comment]
@BenDol I have migrated now the autocomplete from 1.4.0 to 1.5.0.

**Comment by guaido79** [comment]
Replaced by https://github.com/GwtMaterialDesign/gwt-material-addins/pull/9

**Pull request closed without merging**
