### PR TITLE
Added methods from the ListBox to the MaterialListBox.

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
Added methods from the ListBox class from GWT to the MaterialListBox (since MaterialListBox doesn't extend ListBox anymore).

Also added javadocs to the delegate methods, and created some utility methods for easier use of the component.

Original pull request: #246.

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
@kevzlou7979 What do you mean by nested feature?

**Comment by kevzlou7979** [comment]
@gilberto-torrezan
Support for UiBInder to declare material listbox items. 
Like for example:

```
<m:MaterialListBox>

   <item>Sample</item>
   <item>Sample</item>
   <item>Sample</item>

</m:MaterialListBox>

```

**Comment by gilberto-torrezan** [comment]
Well I didn't change anything related to that, just added the missing methods and added some new utility methods.

**Comment by kevzlou7979** [comment]
Ok no problem.

**Comment by kevzlou7979** [comment]
Will merge now this pr, thanks again

**Comment by gilberto-torrezan** [comment]
Is that something that still doesn't work today or something that work and you are just making sure it didn't break?

**Comment by kevzlou7979** [comment]
Populating listbox on Java side is ok but I dont have any idea how we can do it on UiBInder side. THeres a UiChild Parser there but i dont have any success to do it. https://code.google.com/p/google-web-toolkit/source/browse/trunk/user/src/com/google/gwt/uibinder/elementparsers/UiChildParser.java?r=10716&spec=svn10716

But I think , on Java side its 100% working with it comes to use addItem(String item) method

**Comment by gilberto-torrezan** [comment]
Ok, I can take a look on this till the end of the day. I'll make another PR if I get it running.

**Comment by kevzlou7979** [comment]
@gilberto-torrezan Thank you very much, I am also pushing this PR on release 1.5

**Pull request merged**
