### PR TITLE
Material pager

### PR DESCRIPTION
**Pull request by guaido79**
new component!
I've PR the small fix on master, but for bigger work I need to go on release_1.5, because is the version we use.

### CODE REVIEW

**Comment by BenDol** [comment]
Thanks for the contribution @guaido79 are you able to provide a screen shot of what it looks like? Thanks!

**Comment by kevzlou7979** [comment]
@guaido79 Yeah I agree with @BenDol please provide screenshot :) .Thanks
for the contribution

**Comment by guaido79** [comment]
Here is the screenshot:
image

Generated code:
```html
<ul class="pagination waves-default col s6">
      <li class="waves-effect"><a style="cursor: pointer;"><i class="material-icons" style="cursor: pointer;">chevron_left</i></a>
      </li>
      <li class="waves-effect"><a style="cursor: pointer;"><span>1</span></a></li>
      <li class="waves-effect"><a style="cursor: pointer;"><span>2</span></a></li>
      <li class="waves-effect"><a style="cursor: pointer;"><span>3</span></a></li>
      <li class="waves-effect"><a style="cursor: pointer;"><span>4</span></a></li>
      <li class="waves-effect"><a style="cursor: pointer;"><span>5</span></a></li>
      <li class="waves-effect"><a style="cursor: pointer;"><span>6</span></a></li>
      <li class="waves-effect active"><a style="cursor: pointer;"><span>7</span></a></li>
      <li class="waves-effect"><a style="cursor: pointer;"><span>8</span></a></li>
      <li class="waves-effect"><a style="cursor: pointer;"><span>9</span></a></li>
      <li class="waves-effect"><a style="cursor: pointer;"><span>10</span></a></li>
      <li class="waves-effect"><a style="cursor: pointer;"><i class="material-icons" style="cursor: pointer;">chevron_right</i></a>
      </li>
      <li>
        <div class="chip" style="background-color: inherit;"><span>Page 7 of 100</span></div>
      </li>
    </ul>
```

**Comment by BenDol** [comment]
Looks great, thanks :+1: we will merge this and give it a test run for 1.5 release.

**Comment by guaido79** [comment]
:+1:

**Pull request merged**
