### PR TITLE
MaterialModalBuilder for easy Modal creation

### PR DESCRIPTION
**Pull request by wassx**

### CODE REVIEW

**Comment by BenDol** [comment]
I like the idea of builders for these kinds of components, @gilberto-torrezan makes a valid point, if you could ensure there are no issues with multiple declarations first. Thanks for the contribution!

**Comment by kevzlou7979** [comment]
Thanks for the contribution !

**Comment by BenDol** [comment]
@wassx have you been able to test this out as mentioned above?

**Comment by wassx** [comment]
I fixed the instance handling so only one instance of the materialmodal is created. Works pretty well.
Still I'm facing an issue with the "glass panel". When creating for testing 2 panels and show them immediately one after another, the second call of the modal is used, but when dismissed the glasspanel of the first call is still there. Any ideas how to fix that?
I tried to automatically close the modal when a new "create" is called, but this results in another unwanted behaviour.

**Comment by BenDol** [comment]
Have you tried creating a new MaterialModal rather than reusing the same instance? Not sure if it will resolve the problem though.

**Comment by wassx** [comment]
I ran into the issue, that i would have to replace the MaterialModal from the RootPanel each time... I'll give it another try.

**Comment by wassx** [comment]
The issue with the "glasspanel" called "overlay" is rooted in the materialize.css. It's already filed in their repo: https://github.com/Dogfalo/materialize/issues/2354

**Comment by kevzlou7979** [comment]
@wassx Thanks for the info

**Comment by wassx** [comment]
@gilberto-torrezan I have it from the docu of "openmodal" in MaterialModal class. It seems to be convenient to me to use blocking modals (in terms of darkening the screen and breaking interaction flow) only on "full screen". If needed otherwise, you can just pass a parent param where the modal should sit on.

**Comment by gilberto-torrezan** [comment]
@wassx Thanks for fixing a bug, but when you have a PR opened, new commits to the same branch goes to the same PR. In this case the "MaterialModalBuilder for easy Modal creation" was mixed with your bug fix on AbstractIconButton.java.

A good strategy is to open a new branch on your fork for each pull request you want to make. GitHub also provides a fast way to remove that branch once the pull request is accepted. ;-)

**Pull request closed without merging**
