### PR TITLE
Removed seld-hosted materil-icons

### PR DESCRIPTION
**Pull request by paulux84**
Removed seld-hosted materil-icons.css in favour of Google Web Fonts material icons

### CODE REVIEW

**Comment by kevzlou7979** [comment]
Why we need to remove self hosted icons, we all know that other apps can be used on offline. Sorry but i dont agree if we remove the self hosted icons. @BenDol what will be your opinion?

**Comment by paulux84** [comment]
@kevzlou7979 you are right! but...how you can fix this problem with selfosted material-icons.css?
To do so we need to create multiple material-icons.css based on browser (ex. material-icons-ios.css) and load durig resource injection.
Another way is to do so only for ios (on ios google return the following:

```
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: local('Material Icons'), local('MaterialIcons-Regular'), url(https://fonts.gstatic.com/s/materialicons/v16/2fcrYFNaTjcS6g4U3t-Y5RV6cRhDpPC5P4GCEJpqGoc.woff) format('woff');
}

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
}
```

**Comment by gilberto-torrezan** [comment]
IMO we should provide ways to allow the user to self host or use the remote CSS. Something like we do with jQuery.

**Comment by BenDol** [comment]
Please test my latest changes and let me know if it works now.

**Comment by paulux84** [comment]
@BenDol not work ...sigh sigh

**Comment by BenDol** [comment]
Can't see what the difference is. I have patched the wof2 file with the google one linked and then updated the css file also to match. Very strange.

**Comment by BenDol** [comment]
Ah I see that IOS runs `.woff not `.woff2` I've updated the woff file now. Can you pull the changes and test? The demo will redeploy soon also (but has to recompile and upload first).

**Comment by paulux84** [comment]
I haven't access to browserstack outside my office. You must wait another time tomorrow morning...sorry.
P.s. Remember that in some condition ios9 safari work, but not ios9 chrome.

Il 24 maggio 2016 21:46:25 CEST, Ben Dol <notifications@github.com> ha scritto:
>Ah I see that IOS runs `.woff` not `.woff2` I've updated the woff file
>now. Can you pull the changes and test? The demo will redeploy soon
>also (but has to recompile and upload first).
>
>Edit: the demo snapshot is updated. Please let me know (I am working on
>setting up an iOS9 simulator at the moment)
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/GwtMaterialDesign/gwt-material/pull/330#issuecomment-221374642

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by paulux84** [comment]
@BenDol great news! It works...on chrome and safari on IOS9 :dart: 
You are the best

**Comment by kevzlou7979** [comment]
@paulux84 Ok this issue has been resolved and we can close this PR.

**Comment by BenDol** [comment]
@paulux84 Updated the woff2 and woff files to use the google font api versions and updated the material-icons.css.

**Comment by paulux84** [comment]
@BenDol this is the first thing that i've tried without success...strange.

**Pull request closed without merging**
